import type { Metadata } from "next";
import localFont from "next/font/local";
import { Roboto } from "next/font/google";
import "./globals.css";

const notoSerifKhmer = localFont({
  src: "./fonts/NotoSerifKhmer.ttf",
  variable: "--font-noto-serif-khmer",
  weight: "400",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSerifKhmer.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
